window:
  padding:
   x: 50
   y: 50

  dynamic_padding: true
  decorations: full
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty

font:
  normal:
    family: UW Ttyp0
    style: Bold
  bold:
    family: UW Ttyp0
    style: Bold
  italic:
    family: UW Ttyp0
    style: Italic
  offset:
        x: 0
        y: 0

draw_bold_text_with_bright_colors: true

schemes:
    tropical: &tropic
        primary:
            background: '0x0f0f0f'
            foreground: '0xf0f0f0'

        normal:
            black:   '0x262626'
            red:     '0xcb3333'
            green:   '0xa9e182'
            yellow:  '0xe1b982'
            blue:    '0x82a9e1'
            magenta: '0xb982e1'
            cyan:    '0x82e1b9'
            white:   '0xf0f0f0'
  
        bright:
            black:   '0x262626'
            red:     '0xf23d3d'
            green:   '0xa9e182'
            yellow:  '0xe1b982'
            blue:    '0x82a9e1'
            magenta: '0xb982e1'
            cyan:    '0x82e1b9'
            white:   '0xf0f0f0'

    shrine_d: &dark
        primary:
            background: '0x000000'
            foreground: '0xebebeb'

        normal:
            black:   '0x1d3232'
            red:     '0xcb3333'
            green:   '0x6e9946'
            yellow:  '0xb38e3e'
            blue:    '0x4a6891'
            magenta: '0x803E72'
            cyan:    '0x66808c'
            white:   '0xbebebe'

        bright:
            black:   '0x324949'
            red:     '0xf23d3d'
            green:   '0x86bd55'
            yellow:  '0xd9ad4d'
            blue:    '0x647da5'
            magenta: '0xa65295'
            cyan:    '0x82a2b2'
            white:   '0xe6e6e6'

    shrine_l: &light
        primary:
            background: '0xfafafa'
            foreground: '0x3e3636'

        normal:
            black:   '0xa6a6a6'
            red:     '0xcb3333'
            green:   '0x6e9946'
            yellow:  '0xb38e3e'
            blue:    '0x4a6891'
            magenta: '0x803E72'
            cyan:    '0x66808c'
            white:   '0x1d3232'

        bright:
            black:   '0xa6a6a6'
            red:     '0xf23d3d'
            green:   '0x86bd55'
            yellow:  '0xd9ad4d'
            blue:    '0x647da5'
            magenta: '0xa65295'
            cyan:    '0x82a2b2'
            white:   '0xebebeb'

colors: *tropic

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style: Underline
  unfocused_hollow: true
